dist: trusty

# Sudo is required for docker daemon
sudo: required

language: node_js

# Enable Docker
services:
  - docker

git:
  depth: 5

notifications:
  email: false

# Allow building on the following branches only
# the regular expression on the end is for TAGS because
# when a tag is deployed, it is treated also as a branch
# in these scripts (i.e, $TRAVIS_TAG = $TRAVIS_BRANC)
branches:
  only:
  - master
  - stable
  - petong/travis-ci
  - "/^v\\d+\\.\\d+\\.\\d+(-\\d+)?$/"

# NodeJS Versions
# This will automatically detect yarn support and run yarn for us
node_js:
- '8'

# Scripts that will be run during the test phase. If this phase doesn't
# complete the deploy phase will not run
script:
- npm run lint
- istanbul cover -x "**/seeds/**" -x "**/migrations/**" --include-all-sources --root ./build ./node_modules/mocha/bin/_mocha test --report lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

# Build docker image and push
deploy:
  provider: script
  skip_cleanup: true
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
          npm run docker:release:stable;
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH=stable || $TRAVIS_BRANCH=petong/travis-ci

env:
  global:
    - DOCKER_USERNAME=augurintegration
    - secure: "gtWPYRgm/WP9UurlzyBDODGdyFMSN4nncxC2aNtCNHzucs1PKh0dY6Uj4fUMAZObCpZ4foTpUJHG8BXTWgEgxuT/m3dlTILOSXbtMdFbKuxHE5sbgxuCWhwWuECkeoAcDmG+yZLaX+xuB+sde3aduIouwSlerJvrLw4yDveTC2FVeHbudNt641EeTGFmtJds645rMzeZfyCGKZqlzF5Rz1jWUVQ9GjTU1tx8PLcQcIPxku5z5aXx8l/ZZLN/yodN/LumZYLQrI973bz1xnFJ5NMyFHRkaOIhZAQ0Nwyr1sXUwVdqKbqg2yxDifQunV0Rn//jGRNouBdcWowmsBZw29LeA0fLRt7RTKFaLgPTJ7BeP0d3ySVo+RmW0X2iJ8fB9G7G8cjNujCrEseMaIuYRPeA4dHW8ggC0ax0Knl50dsCOxrjzh46yyc1FT8gZq/TJWdTM1v3PjmS497Y76gyQNe6xAmX8xtYd4DeeV3YaC2Vm1j2HRZCODuOdWCCX5aZ9+vUgs6/5IsDelIeyOnMeeDjCwvWzd9CTeC0u3TMgSRkKzd87BEtjI5gL5mhImnDSZgXh5XvLQQAsWzLpZTns0K/L3v/h8iZYAei8VXmKq+QAJ7Nqs7mNoU6N6j4r1CT0W315wid/thd/fawUWnFlE/vuz3GKRzff723XN63e/E="

