sudo: false

language: node_js

node_js:
  - "8"
  - "6"

before_script:
  - npm install

script:
  - npm run lint
  - istanbul cover -x "**/seeds/**" -x "**/migrations/**" --include-all-sources --root ./build ./node_modules/mocha/bin/_mocha test --report lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
